routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*  URL del Home */

Route::get('/', 'WelcomeController@index')->name('/');

Route::get('/barberia', 'WelcomeController@viewbarberia')->name('Barberia');
Route::get('/tattoo', 'WelcomeController@viewtattoo')->name('Tattoo');
Route::get('/blog', 'WelcomeController@viewblog')->name('Blog');
Route::get('/contactanos', 'WelcomeController@viewcontact')->name('Contact');

/*  URL del login */
Auth::routes();

/*  URL del Admin */
/*  URL del Admin - todos los roles*/
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('citas', 'CitaController');
Route::resource('reportes', 'ReporteController');
route::get('/pdf', 'ReporteController@PDF')->name('descargarPDF');

/*  URL del Admin - Rol Admin*/
Route::group(['middleware' => 'admin'], function () {

    Route::resource('usuarios', 'UserController');
    Route::resource('portafolios', 'PortafolioController');
    Route::resource('expertos', 'ExpertoController');
    Route::resource('servicios', 'ServicioController');
});

app/Portafolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Portafolio extends Model
{
    protected $fillable = [
        'id', 'name', 'imagen', 'categoria_id', 'detail'
    ];

    public function categoria()
    {
        return $this->belongsTo(Categoria::class);
    }
}

app/Http/Controllers/PortafolioController.php
<?php

namespace App\Http\Controllers;

use App\Portafolio;
use App\Categoria;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Storage;


class PortafolioController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $portafolio = Portafolio::latest()->paginate(5);

        return view('portafolios.index', compact('portafolio'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = Categoria::all();

        return view('portafolios.create', compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $artuculo = new Portafolio();

        $img = $request->file('imagen')->store('public/img');
        $imagen = Storage::url($img);

        $artuculo->name = $request->name;
        $artuculo->imagen = $imagen;
        $artuculo->categoria_id = $request->categoria_id;
        $artuculo->detail = $request->detail;
        $artuculo->save();

        return redirect()->route('portafolios.index')
            ->with('success', 'Producto creado con éxito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Portafolio  $portafolio
     * @return \Illuminate\Http\Response
     */
    public function show(Portafolio $portafolio)
    {
        return view('Portafolios.show', compact('portafolio'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Portafolio  $portafolio
     * @return \Illuminate\Http\Response
     */
    public function edit(Portafolio $portafolio)
    {
        $categorias = Categoria::all();

        return view('portafolios.edit', compact('portafolio'), compact('categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Portafolio  $portafolio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Portafolio $portafolio)
    {

        $portafolio->update();

        $img = $request->file('imagen')->store('public/img');
        $imagen = Storage::url($img);

        $portafolio->name = $request->name;
        $portafolio->imagen = $imagen;
        $portafolio->categoria_id = $request->categoria_id;
        $portafolio->detail = $request->detail;
        $portafolio->save();

        return redirect()->route('portafolios.index')
            ->with('warning', 'Producto actualizado con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Portafolio  $portafolio
     * @return \Illuminate\Http\Response
     */
    public function destroy(Portafolio $portafolio)
    {
        $portafolio->delete();

        return redirect()->route('portafolios.index')
            ->with('danger', 'Articulo eliminado correctamente');
    }
}

resources/views/portafolios/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <h1>Agregar Producto.</h1>

    <a class="btn btn-primary" href="{{ route('portafolios.index') }}"><i class="bi bi-arrow-left-circle-fill"></i> Volver</a>

    <form action="{{ route('portafolios.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre del producto') }}</label>
            <div class="col-md-6">
                <input id="name" type="text" class="form-control" name="name" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="imagen" class="col-md-4 col-form-label text-md-right">{{ __('Imagen') }}</label>
            <div class="col-md-6">
                <input id="imagen" type="file" class="form-control" name="imagen" accept="image/*" placeholder="imagen" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="etiquetas" class="col-md-4 col-form-label text-md-right">{{ __('Categoria') }}</label>
            <div class="col-md-6">
                <select name="categoria_id" class="form-control" id="sel1" required>
                    <option value=""> ----- Seleccionar -----</option>
                    @foreach($categorias as $categoria)
                    <option value="{{ $categoria['id'] }}">{{ $categoria['name'] }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="detail" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion') }}</label>
            <div class="col-md-6">
                <textarea id="detail" style="height:150px" class="form-control" name="detail" required></textarea>
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary" style="float: right;">
                    {{ __('Register') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/portafolios/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <h1>Editar Artuculo.</h1>

    <a class="btn btn-primary" href="{{ route('portafolios.index') }}"><i class="bi bi-arrow-left-circle-fill"></i> Volver</a>


    <form action="{{ route('portafolios.update',$portafolio->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre del producto') }}</label>
            <div class="col-md-6">
                <input id="name" type="text" value="{{ $portafolio->name }}" class="form-control" name="name" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="imagen" class="col-md-4 col-form-label text-md-right">{{ __('Imagen') }}</label>
            <div class="col-md-6">
                <input id="imagen" type="file" value="{{ $portafolio->imagen }}" class="form-control" name="imagen" accept="image/*" placeholder="imagen" required>
                <img src="{{ $portafolio->imagen }}" width="100%">
            </div>
        </div>

        <div class="form-group row">
            <label for="etiquetas" class="col-md-4 col-form-label text-md-right">{{ __('Categoria') }}</label>
            <div class="col-md-6">
                <select name="categoria_id" class="form-control" id="sel1" required>
                    <option style='display: none' value="{{ $portafolio->categoria_id }}" selected>{{ $portafolio->categoria->name }}</option>
                    <option value=""> ----- Seleccionar -----</option>
                    @foreach($categorias as $categoria)
                    <option value="{{ $categoria['id'] }}">{{ $categoria['name'] }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="detail" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion') }}</label>
            <div class="col-md-6">
                <textarea id="detail" style="height:150px" class="form-control" name="detail" placeholder="Detail" required>{{ $portafolio->detail }}</textarea>
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary" style="float: right;">
                    {{ __('Actualizar') }}
                </button>
            </div>
        </div>
    </form>

</div>
@endsection

resources/views/portafolios/index.blade.php
    @extends('layouts.admin')

    @section('content')
    <div class="container">
        <h1>Portafolio - Productos.</h1>

        <a class="btn btn-success" href="{{ route('portafolios.create') }}" style="float: right;">Agregar Producto</a>

        @if ($message = Session::get('success'))
        <div class="col-sm-10">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif
        @if ($message = Session::get('warning'))
        <div class="col-sm-10">
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif
        @if ($message = Session::get('danger'))
        <div class="col-sm-10">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif

        <table class="table table-bordered">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Descripcion</th>
                <th>categoria</th>
                <th>Fecha</th>
                <th>Acciónes</th>
            </tr>
            @foreach($portafolio as $Producto)
            <tr>
                <th>{{$Producto->id}} </th>
                <td>{{$Producto->name}} </td>
                <td>{{$Producto->detail}} </td>
                <td>{{$Producto->categoria->name}} </td>
                <td>{{$Producto->created_at}} </td>
                <td>
                    <a class="btn btn-info" href="{{ route('portafolios.show',$Producto->id) }}"><i class="bi bi-eye-fill"></i></a>
                    <a class="btn btn-primary" href="{{ route('portafolios.edit',$Producto->id) }}"><i class="bi bi-pencil-fill"></i></a>
                    <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal"><i class="bi bi-eraser-fill"></i></button>
                </td>
            </tr>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" style="text-align: center;">
                            <h3>Esta seguro de eliminar el Producto</h3>
                        </div>
                        <div class="modal-footer">
                            <form action="{{ route('portafolios.destroy',$Producto->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Confirmar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            @endforeach
        </table>
        {!! $portafolio->links() !!}
    </div>

    @endsection

resources/views/portafolios/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <h1>Detalles del Aticulo.</h1>

    <a class="btn btn-primary" href="{{ route('portafolios.index') }}"><i class="bi bi-arrow-left-circle-fill"></i> Volver</a>

    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Nombre del producto</strong>
        <div class="col-md-6">
            {{ $portafolio->name }}
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Imagen</strong>
        <div class="col-md-6">
            {{ $portafolio->imagen }}
            <img src="{{ $portafolio->imagen }}" width="100%">
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">categoria</strong>
        <div class="col-md-6">
            {{ $portafolio->categoria->name }}
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Descripcion </strong>
        <div class="col-md-6">
            {{ $portafolio->detail }}
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Fecha de creacion</strong>
        <div class="col-md-6">
            {{ $portafolio->created_at }}
        </div>
    </div>
</div>

@endsection