routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*  URL del Home */

Route::get('/', 'WelcomeController@index')->name('/');

Route::get('/barberia', 'WelcomeController@viewbarberia')->name('Barberia');
Route::get('/tattoo', 'WelcomeController@viewtattoo')->name('Tattoo');
Route::get('/blog', 'WelcomeController@viewblog')->name('Blog');
Route::get('/contactanos', 'WelcomeController@viewcontact')->name('Contact');

/*  URL del login */
Auth::routes();

/*  URL del Admin */
/*  URL del Admin - todos los roles*/
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('citas', 'CitaController');
Route::resource('reportes', 'ReporteController');
route::get('/pdf', 'ReporteController@PDF')->name('descargarPDF');

/*  URL del Admin - Rol Admin*/
Route::group(['middleware' => 'admin'], function () {

    Route::resource('usuarios', 'UserController');
    Route::resource('portafolios', 'PortafolioController');
    Route::resource('expertos', 'ExpertoController');
    Route::resource('servicios', 'ServicioController');
});

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">


    <!-- full calender  --- modulo citas -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.1/main.css">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.1/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.1/locales-all.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.1/main.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.10.1/main.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.10.1/main.css">


</head>

<body>
    <div id="app" class='dashboard'>
        <div class="dashboard-nav" style="background-position: 100% 0.5px;  font-weight: 900; background-size: cover; color:#bf925b">
            <header>
                <a href="#!" class="menu-toggle" style="color: #bf925b;"> <i class="bi bi-list"></i> </a>
                <a href="#" class="brand-logo" style="color: #bf925b;"> <i class="bi bi-archive"></i> <span>BRAND</span> </a>
            </header>
            <nav class="dashboard-nav-list">

                @if(Auth::check())
                @if(Auth::user()->role_id == 1)
                <a href="{{ route('home') }}" class="dashboard-nav-item"><i class="bi bi-house-door-fill"></i> HOME </a>
                <div class="nav-item-divider"></div>
                <a href="{{ route('portafolios.index') }}" class="dashboard-nav-item"><i class="bi bi-gear"></i> PORTAFOLIO </a>
                <a href="{{ route('expertos.index') }}" class="dashboard-nav-item"><i class="bi bi-gear"></i> PROFESIONALES </a>
                <!--    <a href="#" class="dashboard-nav-item"><i class="bi bi-gear"></i> COTIZACIONES </a> -->
                <a href="{{ route('citas.index') }}" class="dashboard-nav-item"><i class="bi bi-gear"></i> RESERVACIONES </a>
                <a href="{{ route('servicios.index') }}" class="dashboard-nav-item"><i class="bi bi-gear"></i> SERVICIOS </a>
                <a href="{{ route('usuarios.index') }}" class="dashboard-nav-item"><i class="bi bi-gear"></i> USUARIOS </a>
                <a href="{{ route('reportes.index') }}" class="dashboard-nav-item"><i class="bi bi-gear"></i> REPORTES </a>
                @elseif(Auth::user()->role_id == 2)
                <a href="{{ route('home') }}" class="dashboard-nav-item"><i class="bi bi-house-door-fill"></i> HOME </a>
                <div class="nav-item-divider"></div>
                <!--    <a href="#" class="dashboard-nav-item"><i class="bi bi-gear"></i> COTIZACIONES </a> -->
                <a href="{{ route('citas.index') }}" class="dashboard-nav-item"><i class="bi bi-gear"></i> RESERVACIONES </a>
                <a href="{{ route('reportes.index') }}" class="dashboard-nav-item"><i class="bi bi-gear"></i> REPORTES </a>
                <br> <br> <br> <br> <br>
                @endif
                @endif

                <div class="nav-item-divider"></div>
                @guest
                <a href="{{ route('login') }}" class="dashboard-nav-item"><i class="bi bi-person-circle"></i> {{ __('Login') }} </a>

                @if (Route::has('register'))
                <a href="{{ route('login') }}" class="dashboard-nav-item"><i class="bi bi-person-circle"></i> {{ __('Register') }}</a>
                @endif

                @else
                <div class='dashboard-nav-dropdown'>
                    <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle"><i class="bi bi-person-circle"></i> {{ Auth::user()->name }} </a>
                    <div class='dashboard-nav-dropdown-menu'>
                        <a href="{{ route('logout') }}" class="dashboard-nav-dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                        @endguest
                    </div>
                </div>
                <div class="nav-item-divider"></div>
            </nav>
        </div>
        <div class='dashboard-app'>
            <header class='dashboard-toolbar'><a href="#!" class="menu-toggle" style="color: #bf925b;"><i class="bi bi-list"></i></a></header>
            <div class='dashboard-content'>

                @yield('content')

            </div>
        </div>
    </div>
</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/layouts/home.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BET</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow+Condensed:500,600,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('page/css/open-iconic-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('page/css/animate.css') }}">

    <link rel="stylesheet" href="{{ asset('page/css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('page/css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="{{ asset('page/css/magnific-popup.css') }}">

    <link rel="stylesheet" href="{{ asset('page/css/aos.css') }}">

    <link rel="stylesheet" href="{{ asset('page/css/ionicons.min.css') }}">

    <link rel="stylesheet" href="{{ asset('page/css/bootstrap-datepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('page/css/jquery.timepicker.css') }}">


    <link rel="stylesheet" href="{{ asset('page/css/flaticon.css') }}">
    <link rel="stylesheet" href="{{ asset('page/css/icomoon.css') }}">
    <link rel="stylesheet" href="{{ asset('page/css/style.css') }}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="index.html"><span class="flaticon-scissors-in-a-hair-salon-badge"></span>B.E.T</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a href="{{route('/')}}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{{route('Barberia')}}" class="nav-link">Barberia</a></li>
                    <li class="nav-item"><a href="{{route('Tattoo')}}" class="nav-link">Tattoo</a></li>
                    <!--      <li class="nav-item"><a href="{{route('Blog')}}" class="nav-link">Blog</a></li> -->
                    <li class="nav-item"><a href="{{route('Contact')}}" class="nav-link">Contacto</a></li>
                    <li class="nav-item"><a href="{{route('login')}}" class="nav-link">Iniciar sesión</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- END nav -->



                    @yield('content')




                    <footer class="ftco-footer ftco-section">
                        <div class="container">
                            <div class="row mb-5">
                                <div class="col-md">
                                    <div class="ftco-footer-widget mb-4">
                                        <h2 class="ftco-heading-2 logo">HORARIO DE ATENCIÓN</h2>
                                        <table>
                                            <tr>
                                                <th> Lunes:</th>
                                                <td> 08:00 - 14:00 / 15:00 - 21:00 </td>
                                            </tr>
                                            <tr>
                                                <th> Martes:</th>
                                                <td> 06:00 - 14:00 / 15:00 - 21:00 </td>
                                            </tr>
                                            <tr>
                                                <th> Miércoles:</th>
                                                <td> 06:00 - 14:00 / 15:00 - 21:00 </td>
                                            </tr>
                                            <tr>
                                                <th> Jueves:</th>
                                                <td> 08:00 - 14:00 / 15:00 - 22:00 </td>
                                            </tr>
                                            <tr>
                                                <th> Viernes:</th>
                                                <td> 08:00 - 14:00 / 15:00 - 21:00 </td>
                                            </tr>
                                            <tr>
                                                <th> Sábado:</th>
                                                <td> 08:00 - 14:00 / 15:00 - 21:00 </td>
                                            </tr>
                                            <tr>
                                                <th> Domingo:</th>
                                                <td> 08:00 - 14:00 / 15:00 - 21:00 </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md">
                                    <div class="ftco-footer-widget mb-4">
                                        <h2 class="ftco-heading-2">TIENES PREGUNTAS?</h2>
                                        <div class="block-23 mb-3">
                                            <p>B.E.T Barber Shop, barbería, estilo y tatuajes, apuesta por calidad y un excelente servicio</p>
                                            <ul>
                                                <li><span class="icon icon-map-marker"></span><span class="text">Cl. 63 Sur 87-16, Bogotá 110721, Colombia </span></li>
                                                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                                                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                                            </ul>
                                        </div>
                                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft">
                                            <li class="ftco-animate"><a href="https://web.bewe.co/bet-barberia"><span class="icon-twitter"></span></a></li>
                                            <li class="ftco-animate"><a href="https://www.facebook.com/BET_-Barberia-Estilo-Tatuajes-462788604232210/"><span class="icon-facebook"></span></a></li>
                                            <li class="ftco-animate"><a href="https://www.instagram.com/bet.barbershop.29/"><span class="icon-instagram"></span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </footer>



                    <!-- loader -->
                    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
                            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
                            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" />
                        </svg></div>


                    <script src="{{ asset('page/js/jquery.min.js') }}"></script>
                    <script src="{{ asset('page/js/jquery-migrate-3.0.1.min.js') }}"></script>
                    <script src="{{ asset('page/js/popper.min.js') }}"></script>
                    <script src="{{ asset('page/js/bootstrap.min.js') }}"></script>
                    <script src="{{ asset('page/js/jquery.easing.1.3.js') }}"></script>
                    <script src="{{ asset('page/js/jquery.waypoints.min.js') }}"></script>
                    <script src="{{ asset('page/js/jquery.stellar.min.js') }}"></script>
                    <script src="{{ asset('page/js/owl.carousel.min.js') }}"></script>
                    <script src="{{ asset('page/js/jquery.magnific-popup.min.js') }}"></script>
                    <script src="{{ asset('page/js/aos.js') }}"></script>
                    <script src="{{ asset('page/js/jquery.animateNumber.min.js') }}"></script>
                    <script src="{{ asset('page/js/bootstrap-datepicker.js') }}"></script>
                    <script src="{{ asset('page/js/jquery.timepicker.min.js') }}"></script>
                    <script src="{{ asset('page/js/scrollax.min.js') }}"></script>
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
                    <script src="{{ asset('page/js/google-map.js') }}"></script>
                    <script src="{{ asset('page/js/main.js') }}"></script>

</body>

</html>

resources/views/layouts/login.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <style>
        .login,
        .image {
            min-height: 100vh;
        }

        .bg-image {
            background-image: url('https://thumbs.dreamstime.com/b/plantilla-de-afiche-tatuaje-vintage-studio-sobre-fondo-negro-ilustraci%C3%B3n-vectorial-203564322.jpg');
            background-size: cover;
            background-position: center center;
        }
    </style>

</head>

<body>

    <div class="container-fluid">
        <div class="row no-gutter">
            <!-- The image half -->
            <div class="col-md-6 d-none d-md-flex bg-image"> </div>

            <!-- The content half -->
            <div class="login col-md-6 bg-light">

                <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                    <div class="container">

                        <a class="navbar-brand" href="{{ url('/') }}">
                            HOME
                        </a>

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">

                            <ul class="navbar-nav ml-auto">
                                <!-- Authentication Links -->
                                @guest
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                                @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                                @endif
                                @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }}
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                                @endguest
                            </ul>
                        </div>
                    </div>
                </nav>

                <div class="d-flex align-items-center py-5" style="min-height: 90vh;">

                    @yield('content')

                </div>
            </div>
        </div>
    </div>

</body>

</html>