routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*  URL del Home */

Route::get('/', 'WelcomeController@index')->name('/');

Route::get('/barberia', 'WelcomeController@viewbarberia')->name('Barberia');
Route::get('/tattoo', 'WelcomeController@viewtattoo')->name('Tattoo');
Route::get('/blog', 'WelcomeController@viewblog')->name('Blog');
Route::get('/contactanos', 'WelcomeController@viewcontact')->name('Contact');

/*  URL del login */
Auth::routes();

/*  URL del Admin */
/*  URL del Admin - todos los roles*/
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('citas', 'CitaController');
Route::resource('reportes', 'ReporteController');
route::get('/pdf', 'ReporteController@PDF')->name('descargarPDF');

/*  URL del Admin - Rol Admin*/
Route::group(['middleware' => 'admin'], function () {

    Route::resource('usuarios', 'UserController');
    Route::resource('portafolios', 'PortafolioController');
    Route::resource('expertos', 'ExpertoController');
    Route::resource('servicios', 'ServicioController');
});

app/Servicio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Servicio extends Model
{
    protected $fillable = [
        'id', 'title', 'duracion', 'categoria_id', 'precio', 'detail'
    ];

    public function categoria()
    {
        return $this->belongsTo(Categoria::class);
    }
    public function cita()
    {
        return $this->belongsTo('App\Cita');
    }
}

app/Http/Controllers/ServicioController.php
<?php

namespace App\Http\Controllers;

use App\Servicio;
use App\Categoria;
use Illuminate\Http\Request;

class ServicioController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $servicio = Servicio::latest()->paginate(5);

        return view('servicios.index', compact('servicio'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = Categoria::all();

        return view('servicios.create', compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Servicio::create($request->all());

        return redirect()->route('servicios.index')
            ->with('success', 'Servicio creado con éxito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Servicio  $servicio
     * @return \Illuminate\Http\Response
     */
    public function show(Servicio $servicio)
    {
        return view('servicios.show', compact('servicio'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Servicio  $servicio
     * @return \Illuminate\Http\Response
     */
    public function edit(Servicio $servicio)
    {
        $categorias = Categoria::all();

        return view('servicios.edit', compact('servicio'), compact('categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Servicio  $servicio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Servicio $servicio)
    {
        $servicio->update($request->all());

        return redirect()->route('servicios.index')
            ->with('warning', 'Servicio actualizado con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Servicio  $servicio
     * @return \Illuminate\Http\Response
     */
    public function destroy(Servicio $servicio)
    {
        $servicio->delete();

        return redirect()->route('servicios.index')
            ->with('danger', 'Profesional eliminado correctamente');
    }
}

resources/views/servicios/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <h1>Agregar Servicio.</h1>

    <a class="btn btn-primary" href="{{ route('servicios.index') }}"><i class="bi bi-arrow-left-circle-fill"></i> Volver</a>

    <form action="{{ route('servicios.store') }}" method="POST">
        @csrf

        <div class="form-group row">
            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Nombre del Servicio') }}</label>
            <div class="col-md-6">
                <input id="title" type="text" class="form-control" name="title" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="categoria_id" class="col-md-4 col-form-label text-md-right">{{ __('Categoria') }}</label>
            <div class="col-md-6">
                <select name="categoria_id" class="form-control" id="sel1" required>
                    <option value=""> ----- Seleccionar -----</option>
                    @foreach($categorias as $categoria)
                    <option value="{{ $categoria['id'] }}">{{ $categoria['name'] }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="precio" class="col-md-4 col-form-label text-md-right">{{ __('Precio $') }}</label>
            <div class="col-md-6">
                <input id="precio" type="number" class="form-control" name="precio" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="duracion" class="col-md-4 col-form-label text-md-right">{{ __('Duracion del servicio en minutos') }}</label>
            <div class="col-md-6">
                <input id="duracion" type="number" class="form-control" name="duracion" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="detail" class="col-md-4 col-form-label text-md-right">{{ __('Descripción') }}</label>
            <div class="col-md-6">
                <textarea id="detail" style="height:150px" class="form-control" name="detail" required></textarea>
            </div>
        </div>




        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary" style="float: right;">
                    {{ __('Register') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/servicios/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <h1>Editar Servicio.</h1>

    <a class="btn btn-primary" href="{{ route('servicios.index') }}"><i class="bi bi-arrow-left-circle-fill"></i> Volver</a>


    <form action="{{ route('servicios.update',$servicio->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-group row">
            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Nombre del producto') }}</label>
            <div class="col-md-6">
                <input id="title" type="text" value="{{ $servicio->title }}" class="form-control" name="title" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="etiquetas" class="col-md-4 col-form-label text-md-right">{{ __('Categoria') }}</label>
            <div class="col-md-6">
                <select name="categoria_id" class="form-control" id="sel1" required>
                    <option style='display: none' value="{{ $servicio->categoria_id }}" selected>{{ $servicio->categoria->name }}</option>
                    <option value=""> ----- Seleccionar -----</option>
                    @foreach($categorias as $categoria)
                    <option value="{{ $categoria['id'] }}">{{ $categoria['name'] }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="precio" class="col-md-4 col-form-label text-md-right">{{ __('Presio $') }}</label>
            <div class="col-md-6">
                <input id="precio" type="number" value="{{ $servicio->precio }}" class="form-control" name="precio" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="duracion" class="col-md-4 col-form-label text-md-right">{{ __('Duracion del servicio en minutos') }}</label>
            <div class="col-md-6">
                <input id="duracion" type="number" value="{{ $servicio->duracion }}" class="form-control" name="duracion" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="detail" class="col-md-4 col-form-label text-md-right">{{ __('Descripcion') }}</label>
            <div class="col-md-6">
                <textarea id="detail" style="height:150px" class="form-control" name="detail" placeholder="Detail" required>{{ $servicio->detail }}</textarea>
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary" style="float: right;">
                    {{ __('Actualizar') }}
                </button>
            </div>
        </div>
    </form>

</div>
@endsection

resources/views/servicios/index.blade.php
    @extends('layouts.admin')

    @section('content')
    <div class="container">
        <h1>Servicios.</h1>

        <a class="btn btn-success" href="{{ route('servicios.create') }}" style="float: right;">Agregar Servicio</a>

        @if ($message = Session::get('success'))
        <div class="col-sm-10">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif
        @if ($message = Session::get('warning'))
        <div class="col-sm-10">
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif
        @if ($message = Session::get('danger'))
        <div class="col-sm-10">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif

        <table class="table table-bordered">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Precio</th>
                <th>Duracion del servicio</th>
                <th>Categoria</th>
                <th>Fecha</th>
                <th>Acciónes</th>
            </tr>
            @foreach($servicio as $servii)
            <tr>
                <th>{{$servii->id}} </th>
                <td>{{$servii->title}} </td>
                <td>$ {{$servii->precio}} </td>
                <td>{{$servii->duracion}} </td>
                <td>{{$servii->categoria->name}} </td>
                <td>{{$servii->created_at}} </td>
                <td>
                    <a class="btn btn-info" href="{{ route('servicios.show',$servii->id) }}"><i class="bi bi-eye-fill"></i></a>
                    <a class="btn btn-primary" href="{{ route('servicios.edit',$servii->id) }}"><i class="bi bi-pencil-fill"></i></a>
                    <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal"><i class="bi bi-eraser-fill"></i></button>
                </td>
            </tr>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" style="text-align: center;">
                            <h3>Esta seguro de eliminar el Servicio</h3>
                        </div>
                        <div class="modal-footer">
                            <form action="{{ route('servicios.destroy',$servii->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Confirmar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            @endforeach
        </table>
        {!! $servicio->links() !!}
    </div>

    @endsection

resources/views/servicios/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <h1>Detalles del Servicio.</h1>

    <a class="btn btn-primary" href="{{ route('servicios.index') }}"><i class="bi bi-arrow-left-circle-fill"></i> Volver</a>

    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Nombre del Servicio</strong>
        <div class="col-md-6">
            {{ $servicio->title }}
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Categoria</strong>
        <div class="col-md-6">
            {{ $servicio->categoria->name }}
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Precio $</strong>
        <div class="col-md-6">
            {{ $servicio->precio }}
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Duracion del servicio en minutos</strong>
        <div class="col-md-6">
            {{ $servicio->duracion }}
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Descripcion </strong>
        <div class="col-md-6">
            {{ $servicio->detail }}
        </div>
    </div>
    <div class="form-group row">
        <strong class="col-md-4 col-form-label text-md-right">Fecha de creacion</strong>
        <div class="col-md-6">
            {{ $servicio->created_at }}
        </div>
    </div>
</div>

@endsection